### ISSUE TITLE
ReferenceError: Bun is not defined

### ISSUE THREAD

**Issue by vjpr** [jhmaster2000/node-bun#2]
```
ReferenceError: Bun is not defined
    at file:///Users/Vaughan/Library/pnpm/global/5/.pnpm/node-bun@0.5.9-rev.1/node_modules/node-bun/dist/modules/bun.js:1:217
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
```

I like to be explicit about the Bun global:

```
import Bun from 'bun'
```

**Comment by jhmaster2000** [comment]
This is caused by a breaking change in Node v20 which moved loaders to a separate thread, it can be temporarily dealt with by using Node v19 but I'm already working on a fix.

**Comment by jhmaster2000** [comment]
New version on npm `0.6.3` has this fixed. Node v20.2+ is now required.

**Comment by vjpr** [comment]
Regarding your comments here:

https://github.com/jhmaster2000/node-bun/blob/d41db51f518453c18724a80ad6cfd98102a558c8/src/loader.ts#L20-L22

https://github.com/jhmaster2000/node-bun/blob/a5e06906cfb0c91aa17e86b19a2e539781a9fd0b/src/loader.ts#L20-L26

If I understand correctly...you can use the `globalPreload` to access globals in the application (not loader worker) code, by using the `{port}` param. Just remember, `globalPreload` runs in the loader, and the string of code runs in your application...which should listen to a message that sets the global.

https://nodejs.org/api/esm.html#globalpreload

**Comment by jhmaster2000** [comment]
The issue with `globalPreload` is that it runs *before* the first `resolve` hook for the entry file, so we don't yet have the `mainURL` value to use on it. Although you did give me the pretty hacky idea of, *maybe*, if storing the **port** in the top-level of the loader works without breaking it, so that the `resolve` hook can access it and send the message, it could work, but I'm not sure how **port** works exactly. I'll look into it soon.
