### ISSUE TITLE
Use `Bun.Transpiler` instead of `swc`

### ISSUE THREAD

**Issue by vjpr** [jhmaster2000/node-bun#3]

**Comment by jhmaster2000** [comment]
This does not make sense, it is impossible. `node-bun` runs *on Node*, implementing polyfills for Bun APIs, *including* `Bun.Transpiler` itself (via `swc`), one cannot write a polyfill for `Bun.Transpiler` by using `Bun.Transpiler`, or in other words an impossible self-dependency.

Yes, `swc` is not and will never be 1:1 matching in behavior with `Bun.Transpiler`, especially in the transpiled code output, this falls under the 3rd node-bun goal in the README (emphasis added):
> Be functionality matching but **not necessarily 1:1 identical**, there will be quirks in some cases

The goal of the `Bun.Transpiler` polyfill and the TS runtime is to achieve functionality, so as long as the code works and there are no significant runtime behavior differences caused by differences in the transpiled code, it can be considered a working polyfill. Although be aware the `Bun.Transpiler` polyfill is not complete yet, the options object is currently ignored.
