### ISSUE TITLE
Use `bun` to run the entrypoint

### ISSUE THREAD

**Issue by vjpr** [jhmaster2000/node-bun#5]
`cli.ts` seems like it just runs another node process with some flags.

Maybe `bun` should be used for this - it would be faster.

I think there are two separate cases:

1. When `bun` binary is not available in an execution environment.
2. When `bun` apis are used, but the addition of a new feature is not possible without node.js. So `node-bun` would be used until it becomes possible with Bun. (This is where I find myself a lot of the time)

**Comment by jhmaster2000** [comment]
I am not sure you correctly understand the goal of `node-bun`, anything involving using bun itself in any way on this project is already paradoxical, to quote the explicit **non-goals** section of the README:

> * Replace Bun (Bun does much more than just runtime APIs + the many other reasons below)
> * Match native Bun performance (simply not possible)
> * Help run Node.js apps in Bun (Bun itself is already working on this, node-bun is only providing the other way around)

From your case 2, you seem to be looking for something which can *determine whether you need `node-bun` or not* for a project based on which node or bun APIs it uses (?), which would be completely out of scope of this project, it would require static analysis of your project's entire source code and whatnot. It'd be much simpler to just try to run it on Bun and see if it errors out or not. (It would also be very slow to do such static analysis on every entry point run)

Are you by any chance trying to run `cli.ts` with Bun itself? Because that is the exact opposite of the use-case of the project... (and definitely won't work properly)

**Comment by vjpr** [comment]
> determine whether you need node-bun or not

This is what I am primarily looking for, yes. 

---

Say I have `import Bun from 'bun'` and a function using Bun apis that is called conditionally, I would not want the app to not run. 

Ideally the node loader hook could     ignore it...in a similar way that webpack does.

But as you said it's probabaly out of scope. I will start a new project, and potentially rely on the node-bun polyfills.
