### ISSUE TITLE
Separate polyfill and transpilation in loader

### ISSUE THREAD

**Issue by vjpr** [jhmaster2000/node-bun#6]
I maintain my own TS loader (resolve + load). It would be nice to have the loader transpilation code be optional or split off, so that if someone runs their own TS resolver/loader already they can easily drop in *only* the Bun-specific resolver/polyfill stuff from `node-bun`.

**Comment by jhmaster2000** [comment]
Indeed, when I started the project using multiple loaders was not a finished concept/feature on Node's end so I wrote it only considering `node-bun` as the only loader, now that Node stabilized their multiple loaders spec (since v19.6 iirc) making it multiple-loader friendly is a necessary and planned TODO.

It will likely be implemented as different package entry points akin to how `ts-node` offers the `ts-node/esm` loader:
- `node-bun` -> full features (current)
- `node-bun/modules` -> only resolves `bun:` modules

Some use-cases could technically be supported by node-bun as well, such as using it as only a TS loader or CJS resolver, with the Bun features off, but that's just extra maintenance burden for node-bun at no gain from the user using it over a proper loader dedicated for those features like `ts-node` for TS and Node's own [commonjs-extension-resolution-loader](https://github.com/nodejs/loaders-test/tree/main/commonjs-extension-resolution-loader).

**Comment by jhmaster2000** [comment]
Please refer to the deprecation notice on the README.

The official polyfills will not use a loader, so this will inherently be solved. (Note they are not released/usable yet at the time of this post)
